export const SUBMIT_SURVEY_PAGE1 = 'SUBMIT_SURVEY_PAGE1';
export const SUBMIT_SURVEY_PAGE2 = 'SUBMIT_SURVEY_PAGE2';
export const SUBMIT_SURVEY_PAGE3 = 'SUBMIT_SURVEY_PAGE3';
export const SUBMIT_SURVEY_PAGE4 = 'SUBMIT_SURVEY_PAGE4';
export const SAVE_SURVEY_RESPONSES = 'SAVE_SURVEY_RESPONSES';
